
[config_v1]
	#Banned mobs (ex: "minecraft:creeper", "minecraft:zombie"
	bannedMobs = ["minecraft:cave_spider", "minecraft:evoker", "minecraft:illusioner", "minecraft:vex", "minecraft:vindicator", "minecraft:witch", "minecraft:spider", "minecraft:skeleton", "minecraft:creeper"]
	#Mob spawn rates (0.0–1.0, empty = default 1.0)
	spawnRates = []

	[config_v1.spawn_caps_config_v1]
		#Per‑category spawn caps per chunk (ex: "monster=70", "creature=10"). Values outside 0–999 are ignored.
		spawnCaps = ["water_creature=5", "underground_water_creature=5", "ambient=15", "axolotls=5", "creature=10", "water_ambient=20", "monster=70"]

